### ISSUE TITLE
alpheios tools icon doesn't work if no active elements on the page

### ISSUE THREAD

**Issue by balmas** [alpheios-project/embed-lib#56]
I can see the icon anchor on the header in the mobile (Samsung, iPhone). However it does not work in Language,  Authors, Works pages. it does work only in Reader view.

_Originally posted by @monzug in https://github.com/alpheios-project/alpheios_nemo_ui/issues/71#issuecomment-493056971_

**Comment by monzug** [comment]
tested in Samsung and iPhone in text env 1.0.0.14. it works!
