### ISSUE TITLE
simple mode

### ISSUE THREAD

**Issue by balmas** [alpheios-project/embed-lib#65]
Requested by Kevin Ballestrini:

It would be nice to be able to specify "simple mode" for a page, or elements on the page. When in this mode, the only UI to show up would be the short definitions -- the full definitions, grammars, inflection tables, etc. would be hidden.

To consider for the MVP if we have time.

**Comment by balmas** [comment]
qa-3.0.0.61/components 1.2.34

the embedded library can now pass a simpleMode constructor argument to components which will have the following effect:

- the alpheios tools icon is disabled
- the popup and morph panel do not contain define, inflect, usage examples icons
- grammar links still work, but they open the grammar in a panel with no nav bar
- info icon works but opens the help in a panel with no nav bar

@monzug I need to give you something to test the new feature with. But we also need to test that it didn't break anything in the normal mode.

**Comment by monzug** [comment]
so far, it looks all good.

**Comment by balmas** [comment]
ok, you can test simple mode at https://balmas.github.io/alpheios-simple-demo/ (please test on both desktop and mobile)

thank you!

**Comment by monzug** [comment]
info panel needs to be updated as the toolbar icon is disabled and double-click has limited features in simple mode and in useful tips, settings options is mentioned. also, FAQ button should probably be removed.
in mobile, we don't have the help (it would be on the banner but there is no banner). 
on mobile, we have the toolbar icon activated for lookup, on desktop the same icon is disabled but we have the info and lookup icon. for consistency we should probably have the same icons in mobile and desktop, so I would suggest to have the lookup and info icons on mobile, too.

**Comment by balmas** [comment]
>info panel needs to be updated as the toolbar icon is disabled and double-click has limited features in simple mode and in useful tips, settings options is mentioned. also, FAQ button should probably be removed.

My thinking was that if people wanted to use simple mode, they should just override the help with their own.   But perhaps you're right, we should have a default help for it.

>in mobile, we don't have the help (it would be on the banner but there is no banner).
on mobile, we have the toolbar icon activated for lookup, on desktop the same icon is disabled but we have the info and lookup icon. for consistency we should probably have the same icons in mobile and desktop, so I would suggest to have the lookup and info icons on mobile, too.

this is a good point. too.  It's a little more complicated to implement but will investigate if it's possible to do without risking breaking something.

**Comment by balmas** [comment]
I think I would like to defer these two remaining issues with simple mode. We can do an incremental to fix them. I will probably not announce simple mode as a fully released feature. It was an explicit request from a user of the embedded library, so I will ask him to try it out and give us feedback before perfecting it further. I'll enter a new issue so we don't lose track.
